openapi: "3.0.0"
info:
  title: FindNUS Backend API
  description: |
    API documentation for FindNUS backend services.
    Handles the retrieval, processing and management of Lost Items found in NUS.
    Comes with additional spicy features like NLP and elasticsearch.
  version: "0.2-250622"
servers:
  - url: https://findnus.herokuapp.com
    description: Production cluster that is hosting the backend services for FindNUS
  - url: https://uat-findnus.herokuapp.com
    description: User-Acceptance Testing cluster environment for testing

paths:
# These set of paths define debugging endpoints
  /debug/ping:
    get:
      description: |
        Returns a Hello World equivalent message. Shows that the backend connection works.
      responses:
        '200':
          description: A hello world message.
          content:
            text/plain:
              schema:
                type: string
                example: | 
                  message: Hi there, you have reached FindNUS!
  /debug/checkAuth:
    get:
      description: |
        Check with backend if the Firebase token is valid.
      parameters:
      - in: header
        name: Authorization
        description: Firebase ID token of user 
        required: true
        schema:
          type: string
          example: "Authorization: my-firebase-idToken"
      responses:
        '200':
          description: Id token is valid
        '401':
          description: Id token is invalid
  /debug/getDemoItem:
    get:
      description: |
        Get a demo item for Milestone 1. 
      parameters:
      - in: query
        name: name
        description: Name of the demoset item to be retrieved 
        required: true
        schema:
          type: string
        allowReserved: true
      responses:
        '200':
          description: Get request is valid, item is found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Get request is valid, item not found
          content:
            text/plain:
              schema:
                type: string
                example: | 
                  Nothing Found!
# These set of paths define Creation, Update and Delete item operations   
  /item:
    post:
      description: |
        Add new Lost item to be put on Lookout on the database.
      parameters:
      - in: header
        name: Authorization
        description: Firebase ID token of user 
        required: true
        schema:
          type: string
          example: "Authorization: my-firebase-idToken"
      requestBody:
        description: Callback item payload
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/NewItem"
      responses:
        '200':
          description: Item registered into database
        '400':
          description: Rejected new item into database
        '401':
          description: Firebase credentials not invalid
  # /item:
    patch:
      description: |
        Update details of an item on the database.
      parameters:
      - in: header
        name: Authorization
        description: Firebase ID token of user 
        required: true
        schema:
          type: string
          example: "Authorization: my-firebase-idToken"
      - in: query
        name: Id
        description: MongoDB ID of the Item
        required: true
        schema:
          type: string
          example: "Id=629cc52563533a84f60c4c68"
      - in: query
        name: User_id
        description: |
          FindNUS User Id (for lost item lookout requests). Include this to remove from Lost (Lookout) Items collection.
        required: true
        schema:
          type: string
          example: "User_id=196afas7"
      requestBody:
        description: Callback item payload
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/PatchItem"
      responses:
        '200': 
          description: OK
        '401': 
          description: Firebase credentials not invalid
  # /item:
    get:
      description: |
        Get a particular item's full details
      parameters:
        - name: Id
          in: query
          required: true
          description: Item Id reference. Case sensitive.
          schema:
            type: string
            format: string
            minimum: 1
        - name: User_id
          in: query
          description: User_id filter to search for this Id in the LOST collection. Case sensitive.
          schema:
            type: string
            format: string
            minimum: 1
      responses:
        '200':
          description: A Lost Item's details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found
        "500":
          description: Internal server error. Likely to be a message queue fault.
  # /item:
    delete:
      description: |
        Remove an item listing on the database.
      parameters:
        - in: header
          name: Authorization
          description: Firebase ID token of user 
          required: true
          schema:
            type: string
            example: "Authorization: my-firebase-idToken"
        - in: query
          name: Id
          description: MongoDB ID of the Item
          required: true
          schema:
            type: string
            example: "Id=629cc52563533a84f60c4c68"
        - in: query
          name: User_id
          description: |
            FindNUS User_Id (for lost item lookout requests). 
            Include this to remove from Lost (Lookout) Items collection. 
            Case sensitive.
          required: false
          schema:
            type: string
            example: "User_id=196afas7"
      requestBody:
        description: Callback item payload
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/DeleteItem"
      responses:
        '200':
          description: Deletion request received and will be processed if the item exists.
        '401':
          description: Firebase credentials not invalid  
  /item/peek:
    get:
      description: |
        Get a list of lost items sorted by date.
        These items are paginated and filtered by category, if requested.
        The default returns the latest 20 items, with no category filter.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: Number of items to skip (Case sensitive)
          example: offset=10
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of items to return (Case sensitive)
          example: limit=5
        - in: query
          name: category
          schema:
            type: string
          description: |
            Types of category to filter by.
            Chain multiple category values to filter by the
            For example, category=Cards&category=Etc will include results from both Cards and Etc. 
          example: category=Etc
        - in: query
          name: startdate
          schema:
            type: string
          description: |
            String representation of the start date to filter by.
            Date should be in ISO format: YYYY-MM-DDThh:mm:ssZ, eg: 2012:12:25T17:33:59Z
          example: startdate=2012:12:25T17:33:59Z
        - in: query
          name: enddate
          schema:
            type: string
          description: |
            String representation of the end date to filter by. 
            Date should be in ISO format: YYYY-MM-DDThh:mm:ssZ, eg: 2012:12:25T17:33:59Z
          example: enddate=2012:12:25T17:33:59Z
      responses:
        '200':
          description: Returns an array of lost items that may be filtered
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MiniItem'
        "500":
          description: Internal server error. Likely to be a message queue fault.
# These set of paths define querying with a text-based search
  /search:
    get:
      description: |
        Text-based search for an item.
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: |
            Text query to search for lost items. 
            Can be any arbitrary string - the ElasticSearch engine will attempt to best-match the query.
            The query will be performed over the FOUND collection's Name, Category, Location and Item Detail fields.
      responses:
        "200":
          description: Returns an array of Found items that were matched to the query string.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MiniItem'
        "500":
          description: Internal server error. Likely to be a message queue fault.
# These set of paths define the 'smart search' service provided by the lookout microservice
  /lookout:
    get:
      description: |
        Get a list of found items that FindNUS decides are a good possible match to the lost item queried. 
      parameters:
        - in: query
          name: Id
          schema:
            type: integer
          description: Id of the lost item
          example: 82173aiadj
        - in: query
          name: User_id
          schema:
            type: integer
          description: User_id of the lost item's owner
          example: 82173aiadj
      responses:
        '200':
          description: Returns an array of found items that best match the lost item.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MiniItem'
        "400":
          description: Bad request. Missing one or both of User_id and id.
        "500":
          description: Internal server error. Likely to be a message queue fault.
                    
components:
  schemas:
    Item:
      type: object
      description: |
        An Item's schema containing ALL the Lost/Found item's details.
      required:
      - Id
      - Name
      - Date
      - Location
      - Category
      properties:
        Id: 
          type: string
          format: string
          description: The MongoDB ObjectID associated to this Item
          example: 98721yrr0u14oure
        Name:
          type: string
          description: Name of lost/found item
          example: Water Bottle
        Date:
          type: string
          description: Date-time where item is lost/found
          format: date-time
        Location:
          type: string
          description: Where the item was found
          example: E4A DSA Lab
        Category:
          $ref: "#/components/schemas/Category"
          description: Type of item
          example: Cards
        Contact_method:
          $ref: "#/components/schemas/ContactMethod"
          description: Founder/Lostee Contact Method
          example: Telegram
        Contact_details:
          type: string
          description: Contact details of Founder/Lostee
          example: FindNUS
        Item_details:
          type: string
          example: Blue, with a sticker and broken handle
        Image_url:
          type: string
          format: string
          description: Item's accompanying image link
          example: https://imgur.com/gallery/RaHyECD
        User_id:
          type: string
          format: string
          description: UserID associated to this item. Only applicable for Lookout Items.
        Lookout:
          type: boolean
          description: |
            Flag determining whether the Lost item has subscribed to the Lookout service.
            This flag IS REQUIRED.
          example: false
        Pluscode:
          type: string
          description: |
            Pluscode is a string representing the geolocation of a place based on its latitude and longitude.
            Optional parameter if the lost item is tagged to a particular LAT/LONG
          example: 7QXC+CR Singapore
    MiniItem:
      type: object
      description: |
        A truncated form of Item meant for indexing, pagination and carding. 
        Meant to populate frontend search 'cards'. Should come in an array.
      required:
      - Id
      - Name
      - Date
      - Location
      - Category
      properties:
        Id: 
          type: string
          format: string
          description: The MongoDB ObjectID associated to this Item
          example: 98721yrr0u14oure
        Name:
          type: string
          description: Name of lost/found item
          example: Water Bottle
        Date:
          type: string
          description: Date-time where item is lost/found
          format: date-time
        Location:
          type: string
          description: Where the item was found
          example: E4A DSA Lab
        Category:
          $ref: "#/components/schemas/Category"
          description: Type of item
          example: Cards
        Image_url:
          type: string
          format: string
          description: Item's accompanying image link
          example: https://imgur.com/gallery/RaHyECD   
        Pluscode:
          type: string
          description: |
            Pluscode is a string representing the geolocation of a place based on its latitude and longitude.
            Optional parameter if the lost item is tagged to a particular LAT/LONG  
          example: 7QXC+CR Singapore
    NewItem:
      type: object
      description: |
        An Item's schema for POST calls to the backend, for adding NEW items 
        NewItems have two states. They are either a LOST or FOUND item. 
        - LOST: Generated by Losters. Other than the required parameters, **a User_id is required** for Item association to the user.
        - FOUN: Generaterd by Finders. At a minimum, only the required parameters are necessary.
      required:
        - Name
        - Date
        - Location
        - Category
      properties:
        User_id:
          type: string
          description: Unique User_id generated by firebase to associate a user to a Lookout item.
        Name:
          type: string
          description: Name of new lost/found item
          example: Water Bottle
        Date:
          type: string
          description: Date-time where item is lost/found
          format: date-time
        Location:
          type: string
          description: Where the item was found
          example: E4A DSA Lab
        Category:
          $ref: "#/components/schemas/Category"
          description: Type of item
          example: Cards
        Contact_method:
          $ref: "#/components/schemas/ContactMethod"
          description: Founder/Lostee Contact Method
          example: Telegram
        Contact_details:
          type: string
          description: Contact details of Founder/Lostee
          example: FindNUS
        Item_details:
          type: string
          example: Blue, with a sticker and broken handle
        Image_base64:
          type: string
          description: Accompanying image of new Lost/Found item, if applicable
          format: byte
        Lookout:
          type: boolean
          description: |
            Flag determining whether the Lost item has subscribed to the Lookout service.
            This flag should only exist for Lost items.
          example: false
        Pluscode:
          type: string
          description: |
            Pluscode is a string representing the geolocation of a place based on its latitude and longitude.
            Optional parameter if the lost item is tagged to a particular LAT/LONG
          example: 7QXC+CR Singapore
    DeleteItem:
      type: object
      description: |
        An Item's schema for DELETE delete calls to the backend.
      required:
        - Id
      properties:
       Id: 
          type: string
          format: string
          description: The MongoDB ObjectID associated to this Item
          example: 98721yrr0u14oure
    PatchItem:
      type: object
      description: |
        An Item's schema for PATCH calls to the backend, for updatng item details 
        NewItems have two states They are either a LOOKOUT or FOUND item. 
        - LOOKOUT: Generated by Losters. Other than the required parameters, a User_id is necessary for Item association to the user.
        - EXISTING: Generaterd by Finders. At a minimum, only the required parameters are necessary.
      required:
        - Id
      properties:
        Id: 
          type: string
          format: string
          description: The MongoDB ObjectID associated to this Item
          example: 98721yrr0u14oure
        User_id:
          type: string
          description: Unique User_id generated by firebase to associate a user to a Lookout item.
        Name:
          type: string
          description: Name of new lost/found item
          example: Water Bottle
        Date:
          type: string
          description: Date-time where item is lost/found
          format: date-time
        Location:
          type: string
          description: Where the item was found
          example: E4A DSA Lab
        Category:
          $ref: "#/components/schemas/Category"
          description: Type of item
          example: Cards
        Contact_method:
          $ref: "#/components/schemas/ContactMethod"
          description: Founder/Lostee Contact Method
          example: Telegram
        Contact_details:
          type: string
          description: Contact details of Founder/Lostee
          example: FindNUS
        Item_details:
          type: string
          example: Blue, with a sticker and broken handle
        Image_base64:
          type: string
          description: Updated image of Lost/Found item, if applicable
          format: byte
        Lookout:
          type: boolean
          description: |
            Flag determining whether the Lost item has subscribed to the Lookout service.
            This flag should only exist for Lost items.
          example: false
        Pluscode:
          type: string
          description: |
            Pluscode is a string representing the geolocation of a place based on its latitude and longitude.
            Optional parameter if the lost item is tagged to a particular LAT/LONG
          example: 7QXC+CR Singapore
    Category:
      type: string
      enum:
        - Etc
        - Cards
        - Notes
        - Electronics
        - Bottles
      description: Non-case sensitive category name
    ContactMethod:
      type: string
      enum:
        - nus_security 
        - telegram
        - whatsapp
        - wechat
        - line
        - phone_number
      description: Non-case sensitive contact method
  # Define security scheme (Firebase Token)
  # securitySchemes:
  #   firebaseAuth:
  #     type: http
  #     scheme: bearer
