name: Deploy Backend uService to Heroku Production

on:
  push:
    branches:
      - 'main'
    paths:
      - "internal/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Checkout repo
      - name: Checkout
        uses: actions/checkout@v2
  

      - name: CICD Heroku Build Push Release Docker Container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Heroku app.

          # The email address associated with your Heroku account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          email: ${{ secrets.HEROKU_EMAIL }}
          
          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          # Due to the nested nature of the dockerfile, leave it as the project root directory
          dockerfile_directory: "./"

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: "./build/backend.Dockerfile"

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: |
            --no-cache 
            --build-arg GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.FIREBASE_SERVICE_ACCT_PROD }}
          

          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          # For more information look at https://devcenter.heroku.com/articles/process-model
          process_type: web