name: Deploy Item uService to Heroku UAT Env 

on:
  push:
    branches:
      - 'uat'
    paths:
      - "internal/item/**"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Checkout repo
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dockerfile
        run: bash build/setup_item.sh
      - name: Build & Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_UAT }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_heroku_process_type: worker
          docker_build_args: |
            PRODUCTION
            MONGO_URI
            RABBITMQ_URI
            BONSAI_ES_URI
            IMGUR_CLIENT_ID
        env:
          PRODUCTION: false
          MONGO_URI: ${{ secrets.MONGO_URI_DEV }}
          RABBITMQ_URI: ${{ secrets.RABBITMQ_URI_UAT }}
          BONSAI_ES_URI: ${{ secrets.BONSAI_ES_URI }}
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}

