name: Unit-test backend microservice

on:
  pull_request:
    branches:
      - 'uat'
      - 'prod'
    paths:
      - "internal/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Checkout repo
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with: 
          go-version: 1.18

      - name: Build backend uService
        working-directory: ./internal/backend
        run: go build .

      - name: Run Tests
        working-directory: ./internal/backend
        env:
          GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.FIREBASE_SERVICE_ACCT_DEV }}
        run: go test .