name: Unit-test item microservice

on:
  pull_request:
    branches:
      - 'uat'
      - 'main'
    paths:
      - "internal/item/**"

jobs:
  build:
    env:
      PRODUCTION: false
    runs-on: ubuntu-latest
    steps:
      #Checkout repo
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with: 
          go-version: 1.18

      - name: Build backend uService
        working-directory: ./internal/item
        run: go build .

      - name: Run Tests
        working-directory: ./internal/item
        env:
          MONGO_URI: ${{ secrets.MONGO_URI_DEV }}
          RABBITMQ_URI: ${{ secrets.RABBITMQ_URI_UAT }}
        run: go test .