name: Unit-test Item microservice

on:
  pull_request:
    branches:
      - 'dev'
      - 'uat'
      - 'main'
    paths:
      - "internal/item/**"

jobs:
  build:
    env:
      PRODUCTION: false
    runs-on: ubuntu-latest
    steps:
      #Checkout repo
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with: 
          go-version: 1.22

      - name: Build Item uService
        working-directory: ./internal/item
        run: go build .

      - name: Run Tests
        working-directory: ./internal/item
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_DEV_PRIVATE_KEY }}
          FIREBASE_KEY_ID: ${{ secrets.FIREBASE_DEV_PRIVATE_KEY_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI_DEV }}
          RABBITMQ_URI: ${{ secrets.RABBITMQ_URI_UAT }}
          BONSAI_ES_URI: ${{ secrets.BONSAI_ES_URI }}
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: go test .